# 初回マイグレーション。
# `MonitorTarget`, `CheckRun`, `NewItem` のテーブルを作成する。

# Generated by Django 5.2.12 on 2026-03-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2000)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'target_id'],
            },
        ),
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('new_items_count', models.PositiveIntegerField(default=0)),
                ('warning', models.TextField(blank=True)),
                ('raw_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='monitor.monitortarget')),
            ],
            options={
                'ordering': ['-checked_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(blank=True, max_length=2000)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('check_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_items', to='monitor.checkrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
